### ISSUE TITLE
WAR name is not derived properly if the pom contains `finalName` element.

### ISSUE THREAD

**Issue by rsvoboda** [AdamBien/wad#1]
Archive name is resolved by `String thinWARName = currentDirectory + ".war";`
https://github.com/AdamBien/wad/blob/master/src/main/java/wad/App.java#L78

WAR name is not derived properly if the pom contains `finalName` element.
```
    <build>
        <finalName>foo-bar</finalName>
    </build>
```

**Comment by AdamBien** [comment]
Its intentional -> in ThinWARs the artifact id should be the WAR name. In 99% of all my projects it is the case. I like the convention. Thanks for testing!
