### ISSUE TITLE
[rfe] ~/.wadrc config file to add default deployment dirs

### ISSUE THREAD

**Issue by jessefarinacci** [AdamBien/wad#3]
Support very simple `java -jar $WAD_HOME/wad.jar` without having to type every time/project the various locations of target systems.

**Comment by AdamBien** [comment]
This is a good one. A useful feature -> stay tuned :-)

**Comment by AdamBien** [comment]
Implemented in release 0.0.9. Thanks!

**Comment by jessefarinacci** [comment]
Wow, fast turn around. THANKS! 👍
